require: rubocop-rspec

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - oxide.gemspec

Rails/Delegate:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false
