require: rubocop-rspec

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - oxide.gemspec

Style/Copyright:
  Enabled: false

Style/MissingElse:
  Enabled: false
